name: ytdlp2STRM
version: 1.0.0
slug: ytdlp2strm
description: "Youtube / Twitch etc. to STRM files"
url: "https://github.com/fe80Grau/ytdlp2STRM"
init: false
arch:
  - amd64
  - aarch64
ports:
  5000/tcp: 5005
ports_description:
  5000/tcp: Web interface
webui: http://[HOST]:[PORT:5000]
startup: services
options:
  log_level: info
  keep_old_stream: false
  temp_file_duration: 86400
  cron_youtube:
    every: "hours"
    qty: 1
    timezone: "Asia/Seoul"
    do: direct
  cron_twitch:
    every: "hours"
    qty: 1
    timezone: "Asia/Seoul"
    do: direct
  youtube_channel_list:
    - https://www.youtube.com/@LCK
    - https://www.youtube.com/@ytnnews24/streams
  twitch_channel_list:
    - https://www.twitch.tv/riotgames
  # certfile: "fullchain.pem"
  # keyfile: "privkey.pem"
  # ssl: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  host: match(^(?:\d{1,3}\.){3}\d{1,3}$|(?:[\w-]+\.)+[\w-]+$)?
  port: port?
  force_update: bool?
  keep_old_stream: bool?
  temp_file_duration: int?
  cron_youtube:
    every: list(seconds|minutes|hours|days|weeks)
    qty: int(1,60)
    timezone: match(^(Africa|America|Antarctica|Asia|Atlantic|Australia|Europe|Indian|Pacific)/[A-Z][a-zA-Z_]+(?:-[A-Z][a-zA-Z_]+)?$)
    do: list(direct|bridge|download)
  cron_twitch:
    every: list(seconds|minutes|hours|days|weeks)
    qty: int(1,60)
    timezone: match(^(Africa|America|Antarctica|Asia|Atlantic|Australia|Europe|Indian|Pacific)/[A-Z][a-zA-Z_]+(?:-[A-Z][a-zA-Z_]+)?$)
    do: list(direct|bridge|download)
  youtube_channel_list:
    - url
  twitch_channel_list:
    - url
  # certfile: str?
  # keyfile: str?
  # ssl: bool?
map:
  - addon_config:rw
  - media:rw  
  # - ssl